apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-82263855
  namespace: 82263855
  labels:
    app: app-82263855
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-82263855
  template:
    metadata:
      labels:
        app: app-82263855
    spec:
      containers:
      - name: app-82263855
        image: cepgbaseacr.azurecr.io/app-82263855
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-82263855-config
        volumeMounts:
        - name: app-data
          mountPath: /mnt/data
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-82263855-pvc
      imagePullSecrets:
      - name: myregistrykey
