apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-82263855-pvc
  namespace: 82263855
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
