name: CI/CD Pipeline for app-82263855

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Java 환경 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # 배포판 설정

    # 3. Maven으로 빌드
    - name: Build with Maven
      run: mvn clean package

    # 4. Docker 로그인
    - name: Login to Azure Container Registry
      run: |
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.BASEACR_LOGIN_SERVER }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

    # 5. Docker 이미지 빌드 및 푸시
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.STAPACR_LOGIN_SERVER }}/app-82263855:latest .
        docker push ${{ secrets.STAPACR_LOGIN_SERVER }}/app-82263855:latest
