name: Build and Push Docker Image



on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 빌드 컨텍스트 디버깅
      - name: Debug Build Context
        run: |
          echo "Listing files in current directory..."
          ls -la
          echo "Checking .mvn directory..."
          ls -la .mvn
          echo "Checking .mvn/wrapper directory..."
          ls -la .mvn/wrapper

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        env:
          CIACR_LOGIN_SERVER: ${{ secrets.CIACR_LOGIN_SERVER }}
          CIACR_USERNAME: ${{ secrets.CIACR_USERNAME }}
          CIACR_PASSWORD: ${{ secrets.CIACR_PASSWORD }}
        run: |
          echo "${{ secrets.CIACR_PASSWORD }}" | docker login ${{ secrets.CIACR_LOGIN_SERVER }} -u ${{ secrets.CIACR_USERNAME }} --password-stdin
          docker build --no-cache -t ${{ secrets.CIACR_LOGIN_SERVER }}/app-82263855:latest .
          docker push ${{ secrets.CIACR_LOGIN_SERVER }}/app-82263855:latest
