name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 빌드 컨텍스트 디버깅
      - name: Debug Build Context
        run: |
          echo "Listing files in the current directory..."
          ls -la
          echo "Checking .mvn directory..."
          ls -la .mvn
          echo "Checking .mvn/wrapper directory..."
          ls -la .mvn/wrapper

      # 3. Azure Container Registry 로그인
      - name: Login to Azure Container Registry
        env:
          ACR_LOGIN_SERVER: ${{ secrets.BASEACR_LOGIN_SERVER }}
          ACR_USERNAME: ${{ secrets.BASEACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.BASEACR_PASSWORD }}
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # 4. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t ${{ secrets.ACR_LOGIN_SERVER }}/app-82263855:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/app-82263855:latest
